version: "3.7"
services: 
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment: 
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  
  app:
    build: app
    restart: always
    secrets:
      - db-password    
    networks: 
      - backend-network
      - frontend-network

  proxy:
    build: proxy
    restart: always
    ports: 
      - 80:80
    networks: 
      - frontend-network

volumes: 
  db-data:
secrets:
  db-password:
    file: db/secrets.txt
networks:
  backend-network:
  frontend-network: