services: 
  db:
    image: mariadb:11.4
    restart: unless-stopped
    secrets:
      - db-password
      - db-user-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment: 
      MARIADB_DATABASE: example
      TZ: America/Mexico_City
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MARIADB_PASSWORD_FILE: /run/secrets/db-user-password
  app:
    build: app
    restart: always
    secrets:
      - db-password    
    networks: 
      - backend-network
      - frontend-network

  proxy:
    build: proxy
    restart: always
    ports: 
      - 80:80
    networks: 
      - frontend-network

volumes: 
  db-data:
secrets:
  db-password:
    file: db/secrets.txt
  db-user-password:
    file: db/secrets.txt
networks:
  backend-network:
  frontend-network: